### ISSUE TITLE
表达式优先级错误

### ISSUE THREAD

**Issue by fanthos** [avgjs/storyscript#4]
在语法定义中表达式优先级计算错误。比如
1+2*3+4
会被计算成
1+(2*(3+4))

在 https://ohmlang.github.io/editor/ 的示例代码中

```
Exp
  = AddExp

AddExp
  = AddExp "+" MulExp  -- plus
  | AddExp "-" MulExp  -- minus
  | MulExp

MulExp
  = MulExp "*" ExpExp  -- times
  | MulExp "/" ExpExp  -- divide
  | ExpExp

ExpExp
  = PriExp "^" ExpExp  -- power
  | PriExp

PriExp
  = "(" Exp ")"  -- paren
  | "+" PriExp   -- pos
  | "-" PriExp   -- neg
  | ident
  | number
```

能解决这个问题。

**Comment by Icemic** [comment]
Did you mean `#let x = 1 + 2 3 + 4` ( there's a space between 2 and 3 )？

It's not a bug, but a wrong statement, which will cause error in most of programming languages,  ex. Javascript.

Besides, this wrong statement won't be treated as `1+(2(3+4))`, but two statement (`#let x = 1 + 2` and raw text `3 + 4`).

I've added a test case in `test/parser.test.js`, you will get more detail if you search `parse computation`.

Thanks for feedback!

**Comment by fanthos** [comment]
I forgot add \` on the statement. 
There should be a star between 2 and 3.

**Comment by Icemic** [comment]
Oh...I will check it again

**Comment by fanthos** [comment]
Please also make sure expression `3-2+1` works as intended.
