### ISSUE TITLE
Question about name

### ISSUE THREAD

**Issue by stevepeak** [avgjs/storyscript#6]
Hi @Icemi can you contact concerning the project name being Storyscript which conflicts with our project at github.com/storyscript (we also have trademark on `Storyscript`).

We can work something out 😄Thank you for working with us! 👍

**Comment by freewebtime** [comment]
HI, @stevepeak! How can I contact you?

**Comment by stevepeak** [comment]
Please feel free to email me `steve (at) asyncy.com`. 🙏

**Comment by jack-storytailor** [comment]
Is it time to close ticket?
