### ISSUE TITLE
How to write `jump` to other script in storyscript?

### ISSUE THREAD

**Issue by lfkdsk** [avgjs/storyscript#7]
in galgame we may need do a choice to jump to some other scripts, but i didn't fount it in this language spec.

**Comment by Icemic** [comment]
It should be implemented by yourself. For example, create a command named `jump`, write its handler just like how you run the first script:
```js
async function run(scriptString) {
  const story = new StoryScript();
  story.load(scriptString);
  for (const line of story) {
    // ...
    if (line.command === 'jump') {
      nextScript = await fileLoader(line.params.path);
      await run(nextScript);
    }
    //...
  }
}

```

Be aware of `avg-storyscript` is just a parser which doesn't have an runner.
